

/* eslint-disable max-len */
export default {
    namespace: 'dangerousRule',
    message: {
        语法检测表达式: 'GRAMMAR REGEX',
        规则说明: 'EXPLANATION',
        脚本类型: 'SCRIPT TYPE',
        动作: 'ACTION',
        操作: 'ACTIONS',
        '规则的顺位越高，表示执行优先度越高': 'The higher the order of the rules, the higher the detect priority',
        上移: 'Up',
        下移: 'Down',
        删除: 'Delete',
        编辑成功: 'Change has been saved.',
        上移成功: 'Change has been saved(Move Up).',
        下移成功: 'Change has been saved(Move Down).',
        删除成功: 'Rule has been deleted.',
        '确定删除该规则？': 'Are you sure ?',
        脚本编辑器中匹配该规则将不会再收到提醒: 'The editor will no longer be reminded if the rule has been deleted.',
        新增检测规则: 'New Rule',
        扫描: 'Scan',
        拦截: 'Block',
        保存: 'Save',
        取消: 'Cancel',
        '【扫描】': 'SCAN',
        '命中规则的脚本执行任务仅会做记录，不会拦截': 'The script execution task that hits the rule will only be recorded and not be blocked',
        '【拦截】': 'BLOCK',
        '命中规则的脚本执行任务会被记录，并中止运行': 'The script execution task that hits the rule will be recorded and blocked',
        语法检测表达式不能为空: 'Grammar regex is required',
        规则说明不能为空: 'Explanaction is required',
        脚本类型不能为空: 'Script type is required',
    },
};
